### ISSUE TITLE
What is the statistical uniqueness?

### ISSUE THREAD

**Issue by danielabar** [jjt/hashwords#3]
Do you know what is the statistical uniqueness of this? For example, comparing to this python library [humanhash](https://github.com/zacharyvoase/humanhash) that is "1 in 4.3 billion".

**Comment by WorldMaker** [comment]
In the corpus in the repository there are currently 1344 adjectives and 2510 nouns (based on the GitHub's file line count -2 for the array prefix and suffix lines). For combinations of `[adjective] [noun] [noun]` that gives `1344 * 2510 * 2510 = 8467334400` combinations (or ~8.5 billion).

(For comparison humanhash uses a corpus of 256 words and chains four of them for `256 ^ 4` combinations.)

**Comment by danielabar** [comment]
Thanks, this is very helpful.
